trigger:
  branches:
    include:
      - main
      - automation-branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
