trigger:
- automation-branch  # Trigger pipeline for changes in this branch

pool:
  vmImage: 'ubuntu-latest'  # You can adjust the OS image if needed

variables:
  system.debug: true  # Enable detailed logs for troubleshooting

steps:
# Install dependencies, Chrome, and ChromeDriver
- script: |
    sudo apt-get update
    sudo apt-get install -y wget curl unzip
    sudo apt-get install -y google-chrome-stable
    # Download the appropriate version of ChromeDriver based on the installed Chrome version
    CHROME_VERSION=$(google-chrome-stable --version | sed 's/[^0-9]*//g')
    wget https://chromedriver.storage.googleapis.com/$(echo $CHROME_VERSION | cut -c1-3)/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    sudo mv chromedriver /usr/local/bin/
    sudo chmod +x /usr/local/bin/chromedriver
  displayName: 'Install Chrome and ChromeDriver'

# Run Maven build and tests (with headless configuration)
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'  # Specify your desired Java version
    jdkArchitectureOption: 'x64'
    goals: 'clean test'
    options: '-Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Run Cucumber Tests'

# Optionally, add another step to collect test results or perform other actions
