trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest' # Or you can change this to 'windows-latest' or 'macos-latest'

variables:
  chromedriver_version: '113.0.5672.63' # Update this to the version you need
  selenium_version: '4.8.0' # Update this to the version you need
  java_version: '11' # Adjust this as per your project requirements
  maven_version: '3.8.4' # Adjust the Maven version as required

steps:
# Install Java using apt (for Ubuntu-based images)
- script: |
    sudo apt-get update
    sudo apt-get install openjdk-$(java_version)-jdk -y
    java -version
  displayName: 'Install Java $(java_version)'

# Install Maven
- script: |
    wget https://archive.apache.org/dist/maven/maven-3/$(maven_version)/binaries/apache-maven-$(maven_version)-bin.tar.gz
    tar -xvzf apache-maven-$(maven_version)-bin.tar.gz
    sudo mv apache-maven-$(maven_version) /opt/maven
    sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn
    mvn -version
  displayName: 'Install Maven $(maven_version)'

# Install the correct version of chromedriver
- script: |
    curl -sSL https://chromedriver.storage.googleapis.com/$(chromedriver_version)/chromedriver_linux64.zip -o chromedriver.zip
    unzip chromedriver.zip
    chmod +x chromedriver
    sudo mv chromedriver /usr/local/bin/
  displayName: 'Install Chromedriver'

# Run the TestNG regression suite
- script: mvn test -DsuiteXmlFile=testng-regression.xml
  displayName: 'Run TestNG Regression Suite'

# Archive test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/test-*.xml'
    testRunTitle: 'TestNG Regression Tests'
