trigger:
- automation-branch  # This will trigger the pipeline on this branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  system.debug: true  # Enable detailed debug logs for troubleshooting

steps:
# Step 1: List all files to confirm the structure
- script: |
    echo "Listing files to check the structure"
    ls -R $(Build.SourcesDirectory)  # List all files recursively to confirm location of pom.xml
  displayName: 'List files in repository'

# Step 2: Ensure the correct working directory is being used
- script: |
    echo "Current directory is: $(System.DefaultWorkingDirectory)"
    ls -l $(System.DefaultWorkingDirectory)  # List files in the current working directory
  displayName: 'Confirm working directory'

# Step 3: Run Maven command to execute tests (TestRunner class)
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to pom.xml located at the root of the repository
    mavenOptions: '-Xmx3072m'  # Set maximum heap size
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'  # Java version to use (11 in this case)
    jdkArchitectureOption: 'x64'  # JDK architecture (64-bit in this case)
    goals: 'clean test'  # Maven goal to clean and run the tests (TestNG based)
    options: '-DsuiteXmlFile=testng-regression.xml'  # Changed to the custom testng-regression.xml file

# Optional: Step to publish JUnit Test Results (if TestNG is configured with JUnit-compatible output)
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/cucumber-reports.xml'
    mergeTestResults: true
    testRunTitle: 'Cucumber Test Results'
  displayName: 'Publish Test Results'
